import os

SIZE_OF_GET_DOCUMENTS = 100


ELASTICSEARCH_WWW = os.getenv('ELASTICSEARCH_WWW', 'http')
ELASTICSEARCH_HOST = os.getenv('ELASTICSEARCH_HOST', 'localhost')
ELASTICSEARCH_PORT = int(os.getenv('ELASTICSEARCH_PORT', 9200))
ELASTICSEARCH_URI = os.getenv("ELASTICSEARCH_URI",f"{ELASTICSEARCH_WWW}:"
                                                  f"//{ELASTICSEARCH_HOST}:{ELASTICSEARCH_PORT}/")
ELASTICSEARCH_INDEX = os.getenv('ELASTICSEARCH_INDEX', 'meta_data_index')

MOST_DANGEROUS_WORDS = "R2Vub2NpZGUsV2FyIENyaW1lcyxBcGFydGhlaWQsTWFzc2FjcmUsTmFrYmEsRGlzcGxhY2VtZW50LEh1bWFuaXRhcmlhbiBDcmlzaXMsQmxvY2thZGUsT2NjdXBhdGlvbixSZWZ1Z2VlcyxJQ0MsQkRT"

DANGEROUS_WORDS = "RnJlZWRvbSBGbG90aWxsYSxSZXNpc3RhbmNlLExpYmVyYXRpb24sRnJlZSBQYWxlc3RpbmUsR2F6YSxDZWFzZWZpcmUsUHJvdGVzdCxVTlJXQQ=="