
SIZE_OF_GET_DOCUMENTS = 100

import os

ELASTICSEARCH_WWW = os.getenv('ELASTICSEARCH_WWW', 'http')
ELASTICSEARCH_HOST = os.getenv('ELASTICSEARCH_HOST', 'localhost')
ELASTICSEARCH_PORT = int(os.getenv('ELASTICSEARCH_PORT', 9200))
ELASTICSEARCH_INDEX = os.getenv('ELASTICSEARCH_INDEX', 'meta_data_index')